### ISSUE TITLE
Create VibratorManager

### ISSUE THREAD

**Issue by JolieKimy** [HE-Arc/DroppyDrop#3]
This class manages the vibration. (sensor)

We think of a vibrate function that starts a thread. If the thread is running (a vibration is on), it doesn't start another thread.

TODO:
- [x] Create Vibrator
- [x] Using an IntentService to start the vibrator

**Comment by JolieKimy** [comment]
Refer to comment on #1 :

The name Vibrator was already taken by android.os.Vibrator https://developer.android.com/reference/android/os/Vibrator

So, the name of th class is now VibratorManager

**Comment by Skogarmadr** [comment]
Creation of a VibratorService. Instead that we use a thread for launch the vibrator. We use a service who is running in background in any time.
