### ISSUE TITLE
Pause function in GameManager

### ISSUE THREAD

**Issue by JolieKimy** [HE-Arc/DroppyDrop#8]
The pause functionnality blurs the game view and displays the following buttons :
* Resume
* Restart
* Menu

It must save the actual state of the game (level and score object).

For this issue, we need more information about taking a screenshot programatically, blurring an image and how to save datas.

**Comment by Skogarmadr** [comment]
TODO:
- [*] Pause the game when the screen is pressed

**Comment by Skogarmadr** [comment]
When we click on the screen, then a windows pop up and put the game game.
We have 3 options :
* Resume the game, unlock the thread
* Restart the game, we restart the activity
* Exit the game, same use like the back button
